 cat > compose.yaml <<'YAML'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    volumes:
      - todo-mysql-data:/var/lib/mysql
 
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mysql
 
volumes:
  todo-mysql-data:
YAML
